version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic revision --autogenerate &&
              alembic upgrade head &&
              gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000"
    volumes:
      - ./app:/code/app
      - ./migrations/versions:/code/migrations/versions
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${PG_PORT}
    ports:
      - "${PG_PORT}:${PG_PORT}"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    depends_on:
      - web

  redis:
    image: redis:7

volumes:
    postgres_data:
